/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "quiz.h"
#include <strcpy.h:wq>
output_quiz *
quiz_ques_1_svc(void *argp, struct svc_req *rqstp)
{
	static output_quiz  result;

	result.reply="2+2";
	return &result;
}

output_quiz *
quiz_ans_1_svc(input_quiz *argp, struct svc_req *rqstp)
{
	static output_quiz  result;

	/*
	 * insert server code here
	 */

	return &result;
}
