/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "quiz.h"

bool_t
xdr_input_quiz (XDR *xdrs, input_quiz *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->anaswer, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_output_quiz (XDR *xdrs, output_quiz *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->reply, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
