#include <stdio.h>

#include <rpc/rpc.h>    /* standard RPC include file */
#include "calc.h"       /* this file is generated by rpcgen */

main(int argc, char *argv[])
{
    CLIENT *cl;         /* RPC handle */
    char *server;
    float *lresult;      /* return value from bin_date_1() */
    char **sresult;     /* return value from str_date_1() */
    
    if (argc != 2) {
        fprintf(stderr, "usage: %s hostname\n", argv[0]);
        exit(1);
    }
    
    server = argv[1];
    
    /*
     * Create client handle
     */
    
    if ((cl = clnt_create(server, CALC_PROG, CALC_VERS, "udp")) == NULL) {
        /*
         * can't establish connection with server
         */
         clnt_pcreateerror(server);
         exit(2);
    }
    
    /*
     * First call the remote procedure "bin_date".
     */
     input_calc input;
     input.a=2.0;
     input.b=3.0;
     input.op=1;
    if ( (lresult = calculator_1(&input, cl)) == NULL) {
        clnt_perror(cl, server);
        exit(3);
    }
    printf("%f\n",*lresult );
}