/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input_calc {
	float a;
	float b;
	int op;
};
typedef struct input_calc input_calc;

#define CALC_PROG 0x31234568
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCULATOR 1
extern  float * calculator_1(input_calc *, CLIENT *);
extern  float * calculator_1_svc(input_calc *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCULATOR 1
extern  float * calculator_1();
extern  float * calculator_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input_calc (XDR *, input_calc*);

#else /* K&R C */
extern bool_t xdr_input_calc ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
