/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _QUIZ_H_RPCGEN
#define _QUIZ_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input_quiz {
	char answer[256];
	float b;
	float a;
	int op;
};
typedef struct input_quiz input_quiz;

struct output_quiz {
	char answer[256];
	float b;
	int op;
};
typedef struct output_quiz output_quiz;

#define QUIZ_PROG 0x31234568
#define QUIZ_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define QUIZ_QUES 1
extern  input_quiz * quiz_ques_1(void *, CLIENT *);
extern  input_quiz * quiz_ques_1_svc(void *, struct svc_req *);
#define QUIZ_ANS 2
extern  input_quiz * quiz_ans_1(input_quiz *, CLIENT *);
extern  input_quiz * quiz_ans_1_svc(input_quiz *, struct svc_req *);
extern int quiz_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define QUIZ_QUES 1
extern  input_quiz * quiz_ques_1();
extern  input_quiz * quiz_ques_1_svc();
#define QUIZ_ANS 2
extern  input_quiz * quiz_ans_1();
extern  input_quiz * quiz_ans_1_svc();
extern int quiz_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input_quiz (XDR *, input_quiz*);
extern  bool_t xdr_output_quiz (XDR *, output_quiz*);

#else /* K&R C */
extern bool_t xdr_input_quiz ();
extern bool_t xdr_output_quiz ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_QUIZ_H_RPCGEN */
