/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "quiz.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

input_quiz *
quiz_ques_1(void *argp, CLIENT *clnt)
{
	static input_quiz clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, QUIZ_QUES,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_input_quiz, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

input_quiz *
quiz_ans_1(input_quiz *argp, CLIENT *clnt)
{
	static input_quiz clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, QUIZ_ANS,
		(xdrproc_t) xdr_input_quiz, (caddr_t) argp,
		(xdrproc_t) xdr_input_quiz, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
